### ISSUE TITLE
[Bug]: 没有适用于QQ 15820 版本的Patch

### ISSUE THREAD

**Issue by BetterOIer** [mo-jinran/LiteLoaderQQNT#100]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

ac0799b951f4eeb92066dbd38677a5d7da65fe89

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

打开Patch文件夹

### 期望的结果是什么？

有对应9.9.1-15820版本的修补文件

### 实际的结果是什么？

没有找到

### 补充说明（可选）

我想知道9.9.1-15820版本**要查找和替换的字节序列**是什么，谢谢

**Comment by mo-jinran** [comment]
在仓库内有，你需要单独下载 patch.ps1（更建议clone仓库安装，已针对15820适配）

**Comment by BetterOIer** [comment]
> 在仓库内有，你需要单独下载 patch.ps1（更建议clone仓库安装，已针对15820适配）

谢谢帮助
