### ISSUE TITLE
[Bug]: 打开一段时间后闪退

### ISSUE THREAD

**Issue by kiriYui0** [mo-jinran/LiteLoaderQQNT#101]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

启动一段时间后闪退,所有的东西(包括qqnt本体,插件本体,启动器)都是今天下载的最新版

### 期望的结果是什么？

持续运行

### 实际的结果是什么？

闪退

### 日志记录

[Launcher] 开始启动QQ...
[app]module file name: H:\qqnt\QQ.exe
457821688f5fdfaf1d37d349e68b7a6b63c8dff2ebca177923f43cb987fc9191
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
f7ed28ac68f19c0e836789333bfaa38774094317d1b22e510e0a80b89d9cf864
0
[preload] process type:
[app]module file name: H:\qqnt\QQ.exe
[preload] hotupdate base version: 9.9.1-15820
[preload] hotupdate current version: 9.9.1-15820
[preload] install app version: 9.9.1-15820

[preload] succeeded. H:\qqnt\resources\app\versions\9.9.1-15820\major.node
[preload] succeeded. H:\qqnt\resources\app\versions\9.9.1-15820\wrapper.node
[preload] succeeded. H:\qqnt\resources\app\app_launcher\launcher.node
[LiteLoader] Initializing...
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: QQNT微信风格主题
[LiteLoader] Done! 5 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/8/11 15:46:34][INFO] H:\qqnt\resources\app\versions\config.json 存在

[2023/8/11 15:46:34][INFO] H:\qqnt\resources\app\versions\9.9.1-15820.zip 不存在，无法执行解压操作

[2023/8/11 15:46:34][INFO] 从版本目录加载主进程代码: H:\qqnt\resources\app\versions\9.9.1-15820\application\background.js, {
  "curVersion": "9.9.1-15820",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/8/11 15:46:34][INFO]
---------- 华丽的分割线 ----------

Anti-Recall: Loading recalled msgs from db...
Anti-Recall: Loaded 1 msgs.
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
15:46:42.405 > [hot update] hotUpdateApi checkHasMultipleQQ false
15:46:42.406 > [hot update] hotUpdateApi start clearOldVersions
15:46:42.407 > [hot update] hotUpdateApi curVersionZipPath is: H:\qqnt\resources\app\versions\9.9.1-15820.zip false
15:46:42.458 > [hot update] hotUpdateApi checkHasMultipleQQ false
15:46:42.458 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.1-15820
15:46:42.459 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message

**Comment by lkyu-ly** [comment]
确定"没有找到相同问题的ISSUE"吗，请看这里 #93

**Comment by mo-jinran** [comment]
请安装0.5.1版本LiteLoaderQQNT，已解决该问题
