### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#102]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

插件市场更新插件

### 期望的结果是什么？

正常更新

### 实际的结果是什么？

更新重启后依旧需要更新

**Comment by mo-jinran** [comment]
很早注意到了，这属于是那个插件自己的问题，不过插件作者早已修复
