### ISSUE TITLE
[Bug]: QQ闪退

### ISSUE THREAD

**Issue by Xieu233** [mo-jinran/LiteLoaderQQNT#109]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1 15820

### LiteLoaderQQNT 版本 （或 Commit Id）

最新版

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

QQ启动后不到几分钟自动关闭

### 期望的结果是什么？

不会自动关闭

### 实际的结果是什么？

QQ启动后不到几分钟自动关闭

**Comment by shi-an** [comment]
https://github.com/mo-jinran/LiteLoaderQQNT/issues/93

**Comment by mo-jinran** [comment]
请安装0.5.1版本LiteLoaderQQNT，已解决该问题
