### ISSUE TITLE
Mac App Store版QQ已更新

### ISSUE THREAD

**Issue by Bill-Haku** [mo-jinran/LiteLoaderQQNT#110]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

Mac App Store版QQ已更新6.9.18，请更新readme

<img width="937" alt="image" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/48173350/f6485673-429e-40c2-ae01-85ef062715d2">

**Comment by mo-jinran** [comment]
更新什么？

**Comment by Bill-Haku** [comment]
<img width="734" alt="image" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/48173350/fa2c8102-095b-4c27-8e25-a3464d5d1de3">

**Comment by mo-jinran** [comment]
这没问题吧，qq要上架App Store，就得去掉验证

**Comment by Bill-Haku** [comment]
啊？我的意思是应该在readme里面提醒一下Mac用户装App Store版也不行了，得自己找老版本
