### ISSUE TITLE
[Bug]: 最新版本闪退

### ISSUE THREAD

**Issue by LiaoYifan2021** [mo-jinran/LiteLoaderQQNT#111]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-15962 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

最新版本（使用 git clone 的方式安装）

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

运行launcher，打开设置、关于界面（使用一段时间后也会闪退）

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

闪退

### 日志记录

[Launcher] 开始启动QQ...
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
e9c35b64119f4caf1de6a798492f675c9b9dda80ac6812a3dcc5d284f486b126
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
d9533a1b7defaeba31627b2486aa0b38882fcb97f99770cfdc7bbd78da323675
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.2-15962
[preload] hotupdate current version: 9.9.2-15962
[preload] install app version: 9.9.2-15962

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\wrapper.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\major.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at C:\Program Files\Tencent\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: Fluentify
[LiteLoader] Found plugin: 右键高亮
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found plugin: QQ消息修改
[LiteLoader] Found plugin: MSpring Theme
[LiteLoader] Found plugin: Transitio
[LiteLoader] Done! 10 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/8/14 19:04:11][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/8/14 19:04:11][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962.zip 不存在，无法执行解压操作

[2023/8/14 19:04:11][INFO] 从版本目录加载主进程代码: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\application\background.js, {
  "curVersion": "9.9.2-15962",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/8/14 19:04:11][INFO]
---------- 华丽的分割线 ----------

Anti-Recall: Loading recalled msgs from db...
Anti-Recall: Loaded 344 msgs.
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message

**Comment by TW527E** [comment]
至少官網載到的最新版還是 15820
直接去官網載個舊版唄

**Comment by efojug** [comment]
我也有这个问题

**Comment by mo-jinran** [comment]
并未指出支持9.9.2，所以问题无效

**Comment by mo-jinran** [comment]
请安装官网最新版，并使用0.5.1版LiteLoaderQQNT
