### ISSUE TITLE
[Bug]: MacOS QQ Patch

### ISSUE THREAD

**Issue by LXY1226** [mo-jinran/LiteLoaderQQNT#113]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.18-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

3f479a1bdd99eb4bb3cc8bcf5f378e386554309f

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

按照正确方式运行并修改package.json

### 期望的结果是什么？

正确运行并加载Liteloader

### 实际的结果是什么？

闪退？

### 日志记录

不成功的启动：
```
% /Applications/QQ.app/Contents/MacOS/QQ                                    
[app]module file name: 
7189b84298658cd88ba50e479653bbb9e9e58fc586ea12af25279daa15a5e3c0
error code v2:-8
```

成功的启动：
```
% /Applications/QQ.app/Contents/MacOS/QQ                      
[app]module file name: 
f1ba41c2b06f3a10d6c3266f0d1fa843d1d9291652832ba64e16cad003b6d11d
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
6b8860addd6f505244918235bc3a380a6ae96ff5f2ec6099992766a258d34801
0
```

### 补充说明（可选）

看了patch...应该能搞定这件事，最近几天应该能出PR

**Comment by mo-jinran** [comment]
没有Mac设备开发，也不会在Mac下动态调试，只能依靠有Mac的大佬来完善Mac QQNT这方面
而且建议安装App Store版QQNT，貌似并没有添加文件校验

**Comment by LXY1226** [comment]
> 没有Mac设备开发，也不会在Mac下动态调试，只能依靠有Mac的大佬来完善Mac QQNT这方面 而且建议安装App Store版QQNT，貌似并没有添加文件校验

这就去试试，但也会尝试给现在的版本淦个patch进去
