### ISSUE TITLE
[Bug]: 9.9.2-15962崩溃

### ISSUE THREAD

**Issue by RawDiamondMC** [mo-jinran/LiteLoaderQQNT#116]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-15962

### LiteLoaderQQNT 版本 （或 Commit Id）

64ea84f

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

触发方式1：登录QQ后切换到其它窗口
触发方式2：登录后打开设置

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

qq闪退，后台存在QQ进程，后下角无qq图标

### 日志记录

D:\Program Files\Tencent\QQNT>[preload] process type:
[app]module file name: D:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.2-15962
[preload] hotupdate current version: 9.9.2-15962
[preload] install app version: 9.9.2-15962

[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\wrapper.node
[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\major.node
[preload] succeeded. D:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at D:\Program Files\Tencent\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Done! 3 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/8/16 22:03:17][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/8/16 22:03:17][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962.zip 不存在，无法执行解压操作

[2023/8/16 22:03:17][INFO] 从版本目录加载主进程代码: D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-15962\application\background.js, {
  "curVersion": "9.9.2-15962",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/8/16 22:03:18][INFO]
---------- 华丽的分割线 ----------

**Comment by mo-jinran** [comment]
不支持内部版本，仅对已公开版本兼容（也就是官网能下的版本）
