### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tokuda-Harukasora** [mo-jinran/LiteLoaderQQNT#119]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.1

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

打开QQ

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

提示更新LLAPI
![QQ截图20230817204449](https://github.com/mo-jinran/LiteLoaderQQNT/assets/125880096/21c0bd13-71f0-4a53-905e-e4ee821afab5)

### 补充说明（可选）

我找不到任何地方更新LLAPI

**Comment by mo-jinran** [comment]
第三方插件问题，与LiteLoaderQQNT无关
请前往对应插件下提Issue，插件在插件市场更新
