### ISSUE TITLE
[Bug]: 在0.5.1版本中出现了致命错误

### ISSUE THREAD

**Issue by huanlu233** [mo-jinran/LiteLoaderQQNT#120]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1.15880

### LiteLoaderQQNT 版本 （或 Commit Id）

0.51

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

在使用0.5.1版本的时候会出现qq无法启动，报错，已经试过.ps1脚本和LiteLoaderQQNT-Launcher_x64.exe文件（每次报错切换方法时已经卸载qq，重装了的，绝对清理干净了，并且重启了电脑）然后我回退了qq退回了9.9.15717版本，依然报错，然后我就开始尝试32位版本（qq和插件）依然报错。从此，可以得知0.5.1版本可能存在致命的错误（根本无法使用）

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

报错
![260964660-c27fe7e1-9cfc-4ff6-97cf-468c54c954e6](https://github.com/mo-jinran/LiteLoaderQQNT/assets/100133765/0254cbef-552e-42c4-9876-b82b8587ab17)

**Comment by mo-jinran** [comment]
更新 LiteLoaderQQNT 0.5.2 版本解决
