### ISSUE TITLE
[Bug]: 9.9.2-15962依旧闪退

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#121]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-15962

### LiteLoaderQQNT 版本 （或 Commit Id）

d3add491f3045379a27f49f138e4a5c66bc1d580

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

patch安装 启动

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

闪退

### 日志记录

PS D:\QQNT> [preload] process type:
[app]module file name: D:\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.2-15962
[preload] hotupdate current version: 9.9.2-15962
[preload] install app version: 9.9.2-15962

[preload] succeeded. D:\QQNT\resources\app\versions\9.9.2-15962\wrapper.node
[preload] succeeded. D:\QQNT\resources\app\versions\9.9.2-15962\major.node
[preload] succeeded. D:\QQNT\resources\app\app_launcher\launcher.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at D:\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: Chii DevTools
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: Fluentify
[LiteLoader] Found plugin: Claude AI
[LiteLoader] Found plugin: 自定义 CSS 样式
[LiteLoader] Found plugin: 打开链接跳过拦截页
[LiteLoader] Found plugin: 右键高亮
[LiteLoader] Found plugin: 彻底禁用更新
[LiteLoader] Found plugin: Markdown-it
[LiteLoader] Found plugin: 消息靠左连续展示
[LiteLoader] Found plugin: 演示模式
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: QQ增强
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found plugin: QQ消息修改
[LiteLoader] Found plugin: MSpring Theme
[LiteLoader] Found plugin: 复读只因
[LiteLoader] Found plugin: Transitio
[LiteLoader] Found plugin: 窗口置顶
[LiteLoader] Done! 20 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/8/19 18:58:27][INFO] D:\QQNT\resources\app\versions\config.json 存在

[2023/8/19 18:58:27][INFO] D:\QQNT\resources\app\versions\9.9.2-15962.zip 不存在，无法执行解压操作

[2023/8/19 18:58:27][INFO] 从版本目录加载主进程代码: D:\QQNT\resources\app\versions\9.9.2-15962\application\background.js, {
  "curVersion": "9.9.2-15962",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/8/19 18:58:28][INFO]
---------- 华丽的分割线 ----------

Anti-Recall: Loading recalled msgs from db...
Anti-Recall: Loaded 855 msgs.
Page finished loading
Page finished loading
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
Page finished loading
[!Renderer:Log:2] [DeepL] 已检测到 #ml-root .ml-list
[!Renderer:Log:2] [Anti-Recall] 检测到聊天区域，已在当前页面加载反撤回
18:58:35.385 > [hot update] hotUpdateApi checkHasMultipleQQ false
18:58:35.388 > [hot update] hotUpdateApi start clearOldVersions
18:58:35.389 > [hot update] hotUpdateApi curVersionZipPath is: D:\QQNT\resources\app\versions\9.9.2-15962.zip false
18:58:35.437 > [hot update] hotUpdateApi checkHasMultipleQQ false
18:58:35.439 > [hot update] hotUpdateApi checkIsOnErrorVersion null
18:58:35.440 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
[LLAPI] {
  '3e019264-daf9-46dc-a272-7de0758def57': 'LL_DOWN_3e019264-daf9-46dc-a272-7de0758def57'
}
[!Renderer:Log:2] [LLAPI-渲染] 3e019264-daf9-46dc-a272-7de0758def57 undefined
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message

**Comment by FrzMtrsprt** [comment]
+1，9.9.2-15962，未安装任何插件，点击左下角设置或关于时闪退。

**Comment by RubyFox31** [comment]
readme 和 releases 里都有写适配到 9.9.1.15820

**Comment by shi-an** [comment]
> readme 和 releases 里都有写适配到 9.9.1.15820

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/67a03076-9b2d-498e-939f-0a7f7b91cc27)

**Comment by mo-jinran** [comment]
这只是patch支持，与LiteLoaderQQNT无关（

**Comment by mo-jinran** [comment]
不过好消息是刚才已经做出支持
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/66980784/edb8c8f0-e583-4a3e-8f85-0b5f7e891135)

**Comment by ijrou** [comment]
同闪退，，，楼上速速push呀~~~嘿嘿

**Comment by shi-an** [comment]
> 不过好消息是刚才已经做出支持 ![image](https://user-images.githubusercontent.com/66980784/261856065-edb8c8f0-e583-4a3e-8f85-0b5f7e891135.png)

为什么我还闪退

**Comment by mo-jinran** [comment]
才把代码push没多久，并且还没有测试多平台与不同版本的兼容性，目前我推荐用windows最新版QQNT，通过clone安装

**Comment by ijrou** [comment]
> 才把代码push没多久，并且还没有测试多平台与不同版本的兼容性，目前我推荐用windows最新版QQNT，通过clone安装

已经用上了~
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/20642702/e44cf60c-35c1-4570-8446-b01ba2ecd6d2)

**Comment by mo-jinran** [comment]
更新 LiteLoaderQQNT 0.5.2 版本解决
