### ISSUE TITLE
[Bug]: 对 9.9.2-16183 版 QQNT 不生效

### ISSUE THREAD

**Issue by Yave-Yu** [mo-jinran/LiteLoaderQQNT#123]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.1

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

使用安装方法的说明放置的 LiteLoader 文件夹，再用 Launcher 启动的 QQNT，但没出现 LiteLoader 的设置，也没出现 LiteLoader 的数据目录。

### 期望的结果是什么？

能用上 LiteLoader，让我防撤回、禁更新。

### 实际的结果是什么？

没出现 LiteLoader 设置。

**Comment by Boiled-Yakult** [comment]
`LiteLoader`用的哪个？最新的9.9.2-16183要clone仓库的代码，Release还没有上传。
clone最新的仓库 > 复制到QQNT文件夹里 > 运行.ps1 > patch——done > 修改package.json

**Comment by mo-jinran** [comment]
更新 LiteLoaderQQNT 0.5.2 版本解决
