### ISSUE TITLE
[Bug]: 路径错误

### ISSUE THREAD

**Issue by RawDiamondMC** [mo-jinran/LiteLoaderQQNT#124]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

f8979eb

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

启动 QQ。

### 期望的结果是什么？

正常启动。

### 实际的结果是什么？

报错。

### 日志记录

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112449001/c44fbceb-a08a-4df2-8a21-164e4474859f)

### 补充说明（可选）

经测试，为f8979eb造成的问题，使用前一个版本并未出错。

**Comment by mo-jinran** [comment]
应该解决了，尝试更新

**Comment by RawDiamondMC** [comment]
> 应该解决了，尝试更新

没有问题了
