### ISSUE TITLE
[Bug]: Appstore中的QQ版本已经更新到6.9.18

### ISSUE THREAD

**Issue by isTrih** [mo-jinran/LiteLoaderQQNT#125]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.18

### LiteLoaderQQNT 版本 （或 Commit Id）

-

### 运行环境

MacOS

### 运行架构

其它

### 重现步骤

app store自动更新机制，使得已经加载框架的QQnt失效。

### 期望的结果是什么？

想要Mac版破解文件校验的脚本。

### 实际的结果是什么？

可提供Mac编译环境

**Comment by mo-jinran** [comment]
MacOS 的 App Store 内 QQNT 依旧不含文件校验，并且想上架商店就不能加校验
更新 LiteLoaderQQNT 0.5.2 版本解决
