### ISSUE TITLE
[Bug]: 配置界面 和 插件市场 入口无法加载

### ISSUE THREAD

**Issue by ikenxuan** [mo-jinran/LiteLoaderQQNT#128]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.2

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

正常打开qq设置菜单

### 期望的结果是什么？

在LiteLoader 配置界面更新插件

### 实际的结果是什么？

没有LiteLoader **配置界面** 和 **插件市场** 的入口选项，只有之前安装的插件相关配置项

### 日志记录

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112480306/6eb3f1b4-d0a1-470e-aa54-09543fa6d0d8)
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112480306/eebfc1e2-e71f-4d3d-989e-c1e16e0e72a1)

### 补充说明（可选）

使用的修补qq客户端方法

**Comment by mo-jinran** [comment]
通过Clone安装的？还需要拉取子模块才行，并且建议安装Release的新版

**Comment by ikenxuan** [comment]
> 通过Clone安装的？还需要拉取子模块才行，并且建议安装Release的新版

在发布0.5.2的release之前确实是克隆安装的，
目前使用了0.5.2release后问题已经解决，谢谢！
