### ISSUE TITLE
[Bug]: 通过scoop安装的qq-nt打不上patch

### ISSUE THREAD

**Issue by IsaacWangTT** [mo-jinran/LiteLoaderQQNT#136]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2.16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

使用scoop安装qq-nt，然后安装liteloaderqqnt，打上patch.ps1后报错

### 期望的结果是什么？

成功patch

### 实际的结果是什么？

![图片](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69144188/b09cc25d-bdaf-4b7f-8fe6-972e941cec20)

### 补充说明（可选）

因为scoop安装的是便携版，通过解压完成安装的，所以没有动过注册表，故177-188这段代码获取不到安装位置，导致报错，后面我自己直接return了安装路径就成功运行了，后续可以添加用户自己选择路径的选项

**Comment by letterk** [comment]
因为LiteLoader目录的所在位置是固定的
只需要向上回滚几层目录就可以达到通用适配便携版QQNT
