### ISSUE TITLE
[Bug]: 安装完LiteLoader无法接收到消息

### ISSUE THREAD

**Issue by jiyun233** [mo-jinran/LiteLoaderQQNT#172]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

安装完LiteLoader后所有消息全部消失，也无法收到任何新消息，却可以发送消息

### 期望的结果是什么？

原本可以接收到所有的消息

### 实际的结果是什么？

安装完LiteLoader接收不到任何消息，却能发送消息

**Comment by xh321** [comment]
建议完全卸载QQ，并重新安装QQ和框架，不装任何插件，试试看。我目前使用的就是16183，没有问题

**Comment by RinLin-NYA** [comment]
解决该问题的方式：在安装LiteLoaderQQNT项目前先纯净登录一遍9.9.2-16183，再安装LiteLoaderQQNT
