### ISSUE TITLE
[功能提议] 有防撤回吗

### ISSUE THREAD

**Issue by wzhy90** [mo-jinran/LiteLoaderQQNT#28]
搜一圈没找到

**Comment by hugo-Miles** [comment]
提议+1

**Comment by xh321** [comment]
[Anti-Recall](https://github.com/xh321/BetterQQNT-Anti-Recall)
我写了一个简单的，但是由于NTQQ的机制，重新进入页面会导致消息更新，进而导致消息被重新撤回

**Comment by Ritchie1108** [comment]
> [Anti-Recall](https://github.com/xh321/BetterQQNT-Anti-Recall) 我写了一个简单的，但是由于NTQQ的机制，重新进入页面会导致消息更新，进而导致消息被重新撤回

有点危险的做法, 加个撤回消息的存储然后每次页面渲染的时候从里头捞出来恢复?

**Comment by xh321** [comment]
> > [Anti-Recall](https://github.com/xh321/BetterQQNT-Anti-Recall) 我写了一个简单的，但是由于NTQQ的机制，重新进入页面会导致消息更新，进而导致消息被重新撤回
> 
> 有点危险的做法, 加个撤回消息的存储然后每次页面渲染的时候从里头捞出来恢复?

emmm存消息记录可能有泄漏问题吧，而且好麻烦的样子。IPC消息太多了，我暂时没看。我大概猜测重开页面的话，渲染层会从逻辑层重新拉取消息。也就是最开始撤回的是增量更新，重新进入就是全量更新了。
如果逻辑层在接到撤回包后就直接把这条信息删了或者干脆不返回给你了，那确实只能自己存了。但如果不是，还可以从全量更新中筛选出撤回信息并剔除，应该还是可以的。

**Comment by Ritchie1108** [comment]
> > > [Anti-Recall](https://github.com/xh321/BetterQQNT-Anti-Recall) 我写了一个简单的，但是由于NTQQ的机制，重新进入页面会导致消息更新，进而导致消息被重新撤回
> > 
> > 
> > 有点危险的做法, 加个撤回消息的存储然后每次页面渲染的时候从里头捞出来恢复?
> 
> emmm存消息记录可能有泄漏问题吧，而且好麻烦的样子。IPC消息太多了，我暂时没看。我大概猜测重开页面的话，渲染层会从逻辑层重新拉取消息。也就是最开始撤回的是增量更新，重新进入就是全量更新了。 如果逻辑层在接到撤回包后就直接把这条信息删了或者干脆不返回给你了，那确实只能自己存了。但如果不是，还可以从全量更新中筛选出撤回信息并剔除，应该还是可以的。

所以才说是有点危险的做法, 到目前为止几个js的插件应该还都是在操作dom这层吧, break掉撤回的操作应该脑瘫层那边

**Comment by mo-jinran** [comment]
我要准备结束这个issue了，请前往防撤回插件的issue下继续讨论

**Comment by wzhy90** [comment]
现在是完全不写到本地储存聊天记录了？不然可以在收到撤回时把消息同步到本地

XiaoHe321 ***@***.***> 於 2023年7月6日 週四 19:53 寫道：
