### ISSUE TITLE
数据目录无法修改

### ISSUE THREAD

**Issue by lth6268** [mo-jinran/LiteLoaderQQNT#31]
为什么修改了BetterQQNT的数据目录之后点击立即应用，QQ关闭了，再次启动又恢复成了默认地址呢？QQ的版本是9.9.0-14569

**Comment by mo-jinran** [comment]
如果是从终端启动，需要将终端也结束重开

**Comment by mo-jinran** [comment]
正常情况下启动QQNT没有生效的，尝试注销用户重进试试，不行就是bug了

**Comment by mo-jinran** [comment]
（无法复现）

**Comment by longxiaotian799** [comment]
我也是这个问题

**Comment by StudentYee** [comment]
release 版本可正常修改，使用最新编译版本无法修改
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/109954988/5aee637f-3074-40af-9f40-f0707396ceff)

**Comment by mo-jinran** [comment]
尝试使用Release的0.4.0版本
