### ISSUE TITLE
[建议] 能否为窗口之间发送消息提供渠道？

### ISSUE THREAD

**Issue by xh321** [mo-jinran/LiteLoaderQQNT#32]
Electron官方有提到这些内容，需要通过main.js作为中介转发，但需要在main.js里获取对应窗口的对象，再使用xxxWindow.webContents.send。在BetterQQNT中，我不知道如何去获取窗口对象。
是否能提供一下这块的支持？
例如场景：例如在配置界面，设置好参数后，主窗体也能同步更新，而不需要重启程序之类的。

**Comment by mo-jinran** [comment]
https://github.com/mo-jinran/LiteLoaderQQNT-Plugin-Template/wiki/main.js#onbrowserwindowcreated

**Comment by mo-jinran** [comment]
https://www.electronjs.org/zh/docs/latest/api/browser-window#静态方法

**Comment by xh321** [comment]
目前我在窗口创建的时候采用如下方法来获取mainWindow并储存，但还是希望插件能提供相关API，这样可以通过betterQQNT直接获取消息主界面就好了
```
window.webContents.on("did-stop-loading", () => {
        if (window.webContents.getURL().indexOf("#/main/message") != -1) {
            mainWindowObj = window;
        }
    });
```
