### ISSUE TITLE
与BetterQQNT插件不兼容

### ISSUE THREAD

**Issue by MengNianxiaoyao** [mo-jinran/LiteLoaderQQNT#36]
如题，在该插件中我需要的功能没有，但在BetterQQNT中有，两个插件同时使用，BetterQQNT不生效

**Comment by mo-jinran** [comment]
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/66980784/42d9bdb7-bd39-4b18-aced-90a431c043a6)

**Comment by mo-jinran** [comment]
群友给的截图，最新版可以正常加载，就是有一些报错

**Comment by MengNianxiaoyao** [comment]
我这里是开启主题和移除qq游戏中心两个拓展就不生效
