### ISSUE TITLE
插件列表不显示内容

### ISSUE THREAD

**Issue by wsliushiwei** [mo-jinran/LiteLoaderQQNT#44]
之前正常，更新后，误关了依赖的开关，然后出现配置页面进不去，就删除了插件文件夹，结果恢复后导致插件列表所以插件都不显示了，但是插件可以正常运作，也没法卸载重装

**Comment by mo-jinran** [comment]
将数据目录的config.json删除后重启qq

**Comment by wsliushiwei** [comment]
> 将数据目录的config.json删除后重启qq

删除了 但是一样不显示，主题什么的都可以正常使用，但是列表就行不显示内容

**Comment by moshuiNW** [comment]
我这个也不显示 删了config.json重启也还是不显示
![2023-07-17_020630](https://github.com/mo-jinran/LiteLoaderQQNT/assets/110805397/5bfa099b-fc5c-4963-812b-e864e37ce8ec)

**Comment by mo-jinran** [comment]
尝试使用Release的0.4.0版本

**Comment by moshuiNW** [comment]
> 尝试使用Release的0.4.0版本

好像 还是没用👀不显示

**Comment by moshuiNW** [comment]
把数据目录下的config.json添加了一个`"disabled": []`就有效果了(tg上"追风 观影"说的) 
![2023-07-19_073935](https://github.com/mo-jinran/LiteLoaderQQNT/assets/110805397/c6c0b193-d344-4c00-95bc-8c5e9721ae8d)
![2023-07-19_074006](https://github.com/mo-jinran/LiteLoaderQQNT/assets/110805397/d78d7f4b-418f-44b8-81ba-832225fa69b5)

**Comment by lkyu-ly** [comment]
> 尝试使用Release的0.4.0版本

我则是更新4.0之后才不显示的

**Comment by lkyu-ly** [comment]
> 把数据目录下的config.json添加了一个`"disabled": []`就有效果了(tg上"追风 观影"说的) ![2023-07-19_073935](https://user-images.githubusercontent.com/110805397/254424905-c6c0b193-d344-4c00-95bc-8c5e9721ae8d.png) ![2023-07-19_074006](https://user-images.githubusercontent.com/110805397/254424997-d78d7f4b-418f-44b8-81ba-832225fa69b5.png)

好使了，感谢

**Comment by wsliushiwei** [comment]
> > 把数据目录下的config.json添加了一个`"disabled": []`就有效果了(tg上"追风 观影"说的) ![2023-07-19_073935](https://user-images.githubusercontent.com/110805397/254424905-c6c0b193-d344-4c00-95bc-8c5e9721ae8d.png) ![2023-07-19_074006](https://user-images.githubusercontent.com/110805397/254424997-d78d7f4b-418f-44b8-81ba-832225fa69b5.png)
> 
> 好使了，感谢

你现在是啥版本哇 为啥我9.9.1版本直接提示我qq损坏了

**Comment by lkyu-ly** [comment]
@wsliushiwei  9.9.0-14619 具体看这个 #50 最新QQ不能用了

**Comment by mo-jinran** [comment]
已修复，请在插件市场更新或手动安装
