### ISSUE TITLE
似乎是左侧列表不显示了？

### ISSUE THREAD

**Issue by Syunraii** [mo-jinran/LiteLoaderQQNT#45]
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79300447/9842c942-2ffc-4385-b7eb-c4bf5396b4e3)

其实装了以下几个 ：
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79300447/c8f84c80-b9f3-4a7e-aa6d-77683b5bce82)

功能都可以正常使用，是要将这块移动到别的地方么？

**Comment by mo-jinran** [comment]
https://github.com/mo-jinran/LiteLoaderQQNT/pull/42 的新特性
没有配置界面的插件肯定不会出现在左侧插件配置入口
要查看插件请在LiteLoader 配置界面的插件列表处

**Comment by Syunraii** [comment]
建议配置开关选项。
