### ISSUE TITLE
如何刷新页面/打开开发者工具？

### ISSUE THREAD

**Issue by yige-yigeren** [mo-jinran/LiteLoaderQQNT#47]
隔壁有个插件差不多原理，但是可以使用F5刷新页面和F12打开内置开发者工具

**Comment by mo-jinran** [comment]
也是F12

**Comment by yige-yigeren** [comment]
不支持自带的开发者工具吗？

**Comment by mo-jinran** [comment]
腾讯把windows 9.8.5版本以上的devtools彻底删除，无法调用自带devtools，隔壁插件也是依靠chii的远程调试，不过是内置在本体，而LiteLoader需要单独安装chii devtools（因为linux与macos还能开

**Comment by yige-yigeren** [comment]
> 腾讯把windows 9.8.5版本以上的devtools彻底删除，无法调用自带devtools，隔壁插件也是依靠chii的远程调试，不过是内置在本体，而LiteLoader需要单独安装chii devtools（因为linux与macos还能开

哦哦，理解了，谢谢
