### ISSUE TITLE
关于在macOS环境下报错

### ISSUE THREAD

**Issue by ChenniemuCN** [mo-jinran/LiteLoaderQQNT#48]
**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: Cannot find module '/Applications/QQ.app/Contents/Resources/app/app_launcher/LiteLoader'
at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
at node:electron/js2c/browser_init:2:115277
at node:electron/js2c/browser_init:2:115520
at node:electron/js2c/browser_init:2:115524
at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:329:7)
at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
at Module._load (node:internal/modules/cjs/loader:825:15)
at f._load (node:electron/js2c/asar_bundle:2:15017)

**Comment by ChenniemuCN** [comment]
/Applications/QQ.app/Contents/Resources/app/LiteLoader/package.json
`{
    "name": "liteloader-qqnt",
    "version": "0.3.1",
    "description": "QQNT的插件加载器：LiteLoaderQQNT —— 轻量 · 简洁 · 开源",
    "main": "LiteLoader",
    "author": {
        "name": "沫烬染",
        "email": "mojinran@outlook.com"
    },
    "license": "MIT",
    "homepage": "https://github.com/mo-jinran/LiteLoaderQQNT",
    "repository": {
        "type": "git",
        "url": "https://github.com/mo-jinran/LiteLoaderQQNT.git"
    }
}`

**Comment by ChenniemuCN** [comment]
/Applications/QQ.app/Contents/Resources/app/package.json

`{
  "name": "qq-chat",
  "version": "6.9.17-12118",
  "private": true,
  "description": "QQ",
  "productName": "QQ",
  "author": {
    "name": "Tencent",
    "email": "QQ-Team@tencent.com"
  },
  "homepage": "https://im.qq.com",
  "sideEffects": true,
  "main": "./app_launcher/LiteLoader",
  "resolutions": {
    "@tencent/dag-utils": "0.5.16"
  },
  "buildVersion": "12118",
  "isByteCodeShell": true,
  "platform": "darwin",
  "eleArch": "x64"
}`

**Comment by xinyihl** [comment]
"main": "./app_launcher/LiteLoader",
应为
"main": "LiteLoader",

**Comment by ChenniemuCN** [comment]
同样报错

**Comment by xinyihl** [comment]
你不应该修改/Applications/QQ.app/Contents/Resources/app/LiteLoader/package.json改文件

**Comment by xinyihl** [comment]
"main": "LiteLoader",应为
"main": "./src/index.js",
