### ISSUE TITLE
设置里LiteLoader配置界面和市场都不见了

### ISSUE THREAD

**Issue by wzhy90** [mo-jinran/LiteLoaderQQNT#49]
QQ版本是14569，更新到14619也一样，liteloader是直接clone最新的
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/2318890/77697f1f-50af-4d9b-8420-cb87c59d18b9)

**Comment by mo-jinran** [comment]
通过源代码安装，除了需clone仓库，还需拉取submodule，并且给submodule的插件市场安装npm依赖

**Comment by ASC8384** [comment]
> QQ版本是14569，更新到14619也一样，liteloader是直接clone最新的 ![image](https://user-images.githubusercontent.com/2318890/253136622-77697f1f-50af-4d9b-8420-cb87c59d18b9.png)

```
git submodule update --init --recursive
```

**Comment by moshuiNW** [comment]
> > QQ版本是14569，更新到14619也一样，liteloader是直接克隆最新的![图像](https://user-images.githubusercontent.com/2318890/253136622-77697f1f-50af-4d9b-8420-cb87c59d18b9.png)
> 
> ```
> git submodule update --init --recursive
> ```

git完了 安装依赖我直接在目录下执行<npm install>就可以了吗？
