### ISSUE TITLE
最新版ntqq无法启动，提示文件损坏

### ISSUE THREAD

**Issue by forchannot** [mo-jinran/LiteLoaderQQNT#50]
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/100580891/4767d018-347c-4eec-8ae0-7f257ca5328b)
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/100580891/6aac9fc3-3e8a-4e11-8b95-2c0143994ec0)

**Comment by forchannot** [comment]
貌似是给文件加上了签名了

**Comment by ApartTUSITU** [comment]
应该是launcher.json里的？

**Comment by ApartTUSITU** [comment]
{"package.json":"NXStYGEJDfxfP4rtj0ExFJCkRSowU+16UM+SJHBU53SeOJPeLgF7xyJ26qdZjfCD16PPtvf2ncSIShVZv5uZCTmkGVb7Jv74NRxvyZcT11/9dKfSe4rDF6Ar1kb6ythQhHBdsj3IlbnZxR4snykwhcs7KSQuWRoyjxfAtfYBRbwqq4d6lsS9FhgKeCxYRlgqp6Tn0nVpKQWjya3fgzmxnYRGCTGQBhKzm0Wv+AdMbVSQZqCw771/Dc0PXPFD/yv3mYinlzk47DkKlyzRjHkbRr2qfkyvM3nxvsOuAlPvEXlgn1iou9St3Uf4FL6Sy404iXIpIirBeTjgw4ZHgXtYbw==","index.js":"dvV2SJSW/PHDMxjKDSA9GNrsmLQURLn362hGT/nKh2vg7tKh1TMmTCnWIo4+0PHCG1TTCMqm3FoHEokV7tYB8zi39Bum0hpiiHfP8i6c8B6NiPk8f3nq1/HkspaEWj4fAXS3yZilLV2+xR/wPusyIDIjxJSBP7NPCx6a+nS4KJwPdcuM2b1Ny8Q0M7FMVhZB3Nrrk3cIqnaAY6cWFsnD3aqiYOluNTcyGtGqEwOv2F9k5fJCkR9OAFTE/g+LHtp/egXsAKbwEOHq7Y6N6GMcX3vatdVU3p4tm22VgH4T90+GvkWmVGzaWbnVDOAu4jZaUMCGlRJwn7zz671+MFLGlQ==","launcher.js":"FWHf273Mkf0j1tDjeTrVZrn3oqPYLgzeJBbbsmxAWngNW2RgzhOJrFba3bXu/KZ4A2/V97Gsum8XO4IyMbd8OczpuuhUQcPMHRTzmB0Q40iRaxUlJ9lTCnLjk9dh9yYep1kv9lSg6qGOEQxrUzsF3/oyP+CcrSitVQIKnxM+jtmQooAClLERNlqCRpU27rN/7JIVEkesbSma6bA1t4YuSIL2qPtcGeTwBHdjn6762A0nZjW3Psgl/+lO98yXfVGc+ZRtGSsPSMulCF1tq3WxGCNTwJ61eI8Czkrh5KDYGblgQ3pN7CDANC6qWEx4RuwOQ6viAviPv/loi/hFZiQClw==","launcher.node":"WMAZjo0ecd7zAD9WSS5H4MnV8LVcYliAFtgaTCC9skA66LqCTi23PLlZ9R18F/tXAxtjaQO0QDJfyGzwYgKTRcxBNAb/iWIS6UCkKrCJ7ycubXGakEp23ooHwrnU8qaUqTYT8MZE9r8klZ06OVsJhRvifwIma0I/wlruPDxOy5ICvozwVzM4DoXV+kru80pERMZ79DwNJ+0ADVzNYxcdETK4KmgglHHnz/GM5/rPdQn9hWhpJJldiM3rLwmqUFVZHyrt3UMYdeh/vCYXvXcUNiHXkaLCTNtAVZ5VcwkTRp6KUy3EaQX0ReMXGCPxEsvEcWo9Y9X7w2yvymjiZN3Weg=="}

**Comment by ApartTUSITU** [comment]
https://dldir1.qq.com/qqfile/qq/QQNT/bbabcfd7/QQ9.9.0.14569_x64.exe
先用旧版吧

**Comment by ApartTUSITU** [comment]
官网甚至没更新

**Comment by ApartTUSITU** [comment]
launcher.json是9.9.1多出来的

**Comment by TIANLI0** [comment]
新版本给加上签名校验了

**Comment by FW27623** [comment]
新版本已加checksum，想用得回退旧版

**Comment by ApartTUSITU** [comment]
用qqntim吧

**Comment by ApartTUSITU** [comment]
理论上破解掉检测就可以

**Comment by Michaelxia6** [comment]
操了，SBTX

**Comment by ANGJustinl** [comment]
启动方法应该也变了,不走 main: 后面的package.json了(存疑)

**Comment by xh321** [comment]
隔壁QQNTim的方案是直接对QQ.exe进行patch，可以实现，但我觉得大版本更新需要重新patch可能有点麻烦

**Comment by mo-jinran** [comment]
llqqnt跟qqntim在腾讯发布新版后的俩小时内就开始研究实现了绕过，但我最近没时间，不能跟进qqntim发布新版本了，具体可以看qqntim如何实现

**Comment by Cooooldwind** [comment]
xdm隔壁QQNTim貌似也用不了了欸

**Comment by Cooooldwind** [comment]
9.9.1-15293加强了，现在连QQNTim都用不了了......

**Comment by mo-jinran** [comment]
/

**Comment by mo-jinran** [comment]
可进LiteLoader的Telegram群内获取我昨天晚上patch的QQ，不过目前渲染进程有些问题就没法这里

**Comment by Cooooldwind** [comment]
> 可进LiteLoader的Telegram群内获取我昨天晚上patch的QQ，不过目前渲染进程有些问题就没法这里

好的，但是我没有telegram（笑

**Comment by mo-jinran** [comment]
渲染进程也活了,但是目前file://协议有问题,一些插件无法在渲染进程加载文件
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/66980784/31b8e28a-a238-4314-975d-539327c93838)

**Comment by MrLee980** [comment]
> 渲染进程也活了,但是目前file://协议有问题,一些插件无法在渲染进程加载文件 ![image](https://user-images.githubusercontent.com/66980784/255557690-31b8e28a-a238-4314-975d-539327c93838.png)

哈老哥你的15293版本qq可以用吗，我一修改package.json，打开qq就提示文件已损坏

**Comment by xh321** [comment]
> > 渲染进程也活了,但是目前file://协议有问题,一些插件无法在渲染进程加载文件 ![image](https://user-images.githubusercontent.com/66980784/255557690-31b8e28a-a238-4314-975d-539327c93838.png)
> 
> 哈老哥你的15293版本qq可以用吗，我一修改package.json，打开qq就提示文件已损坏

需要给QQ主程序打补丁，相关文件在tg群有

**Comment by mo-jinran** [comment]
更新QQ与LiteLoader到最新版（QQ 9.9.1-15489, LiteLoader 0.5.0）
详细看Release的Note说明
