### ISSUE TITLE
[Bug]: 表情消失了 (QQ自带的EMOJ)

### ISSUE THREAD

**Issue by YuSanr** [mo-jinran/LiteLoaderQQNT#56]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.0-14619

### LiteLoaderQQNT 版本 （或 Commit Id）

0.3.1

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

打开聊天栏
表情
第一个 
打开全部都是空白的
收藏的表情可以看到
Emoj看不见
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112278452/5bb0cb52-4a75-47cb-90e7-1c4081a23743)
试过重装 无效
插件全部卸载无效

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112278452/16f76ae3-a64e-47e7-9a7e-09970453e2d8)

**Comment by jimmieyangcsjs** [comment]
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/45389360/618547b3-b539-4b74-a5ca-ad2215899e9a)
x64的win11 QQNT环境和你一致  建议自查
