### ISSUE TITLE
[Feat]: 一些小的UI改进

### ISSUE THREAD

**Issue by yige-yigeren** [mo-jinran/LiteLoaderQQNT#57]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/53390868/a9941a2e-9237-4358-9ba7-5db203c52cd7)
Liteloader处添加快速转到github的功能
修改目录出添加在explorer中打开的功能

**Comment by yige-yigeren** [comment]
https://github.com/mo-jinran/LiteLoaderQQNT-Config-View/pull/3

自己上手改了

**Comment by mo-jinran** [comment]
打开数据目录功能已在0.1.2实现，请在插件市场内更新
转到github的我想搞一个关于界面，不过暂时没想法
