### ISSUE TITLE
[Bug]: 插件列表显示异常

### ISSUE THREAD

**Issue by xiaozhangup** [mo-jinran/LiteLoaderQQNT#61]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

3.1.1-11223

### LiteLoaderQQNT 版本 （或 Commit Id）

0.4.0

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

启动

### 期望的结果是什么？

插件列表正常显示所有安装的插件

### 实际的结果是什么？

插件列表全部为空

### 补充说明（可选）

插件扩展市场却能知道这个插件安装了/这个没安装

**Comment by mo-jinran** [comment]
请在插件市场内更新配置界面

**Comment by mo-jinran** [comment]
或克隆最新的配置界面仓库到LiteLoader的builtins目录

**Comment by xiaozhangup** [comment]
> 请在插件市场内更新配置界面

更新了，重启后，直接无法点击了
点击没反应

**Comment by mo-jinran** [comment]
请更新QQ与LiteLoader到最新版（Release 0.5.0版本）
