### ISSUE TITLE
[Bug]: QQ设置原本设置项消失

### ISSUE THREAD

**Issue by WM-wuming** [mo-jinran/LiteLoaderQQNT#62]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.0-14619 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

0.4.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

安装LiteLoaderQQNT后打开设置

### 期望的结果是什么？

原本设置项出现

### 实际的结果是什么？

原本不出现

### 日志记录

![296049ea3e36a8dedf9325c91d40de2a](https://github.com/mo-jinran/LiteLoaderQQNT/assets/102670136/2e95bb1d-0628-497c-8e33-c540210165f6)
<img width="632" alt="6914fab5a7ac86fe001967cc1031c3a2" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/102670136/4ac20146-37ec-42d2-bc98-42c721748e9a">

**Comment by bty552** [comment]
我的版本也是: 9.9.0-14619 (64位)
我没有这个Bug，你要不要重新安装QQ试试？

**Comment by lamprose** [comment]
把所有插件删除试一下

**Comment by mo-jinran** [comment]
可以将QQ与LiteLoader更新到最新版
