### ISSUE TITLE
[Bug]: 版本: 9.9.1-15293 (64位)启动错误

### ISSUE THREAD

**Issue by jimmieyangcsjs** [mo-jinran/LiteLoaderQQNT#63]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15293 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

0.40

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

重新安装

### 期望的结果是什么？

恢复正常

### 实际的结果是什么？

报错 显示QQ已损坏

### 日志记录

报错 显示QQ已损坏

### 补充说明（可选）

报错 显示QQ已损坏

**Comment by mo-jinran** [comment]
暂时不支持9.9.1,正在适配中,目前已经快完工了
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/66980784/512e80e0-5c8b-486d-b12f-a1688a312dd3)

**Comment by AwcySama** [comment]
这个版本刚更新没这么快~

**Comment by Winter-is-comingXK** [comment]
作者怎么样了，大概什么时候适配好

**Comment by mo-jinran** [comment]
正在搞了, 完成度差不多90%以上

**Comment by mo-jinran** [comment]
目前可以加载插件,但某些插件可能有一点问题

**Comment by Winter-is-comingXK** [comment]
好的大佬
