### ISSUE TITLE
[Bug]: Mac上QQ无法启动

### ISSUE THREAD

**Issue by Micalhl** [mo-jinran/LiteLoaderQQNT#64]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.18-15293

### LiteLoaderQQNT 版本 （或 Commit Id）

0.4.0

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

- 按照安装步骤正常安装，并调试好 package.json
- 启动 QQ，光标在程序坞光速闪一下然后消失，无任何提示信息

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

启动失败

### 日志记录

![cb212aaf73ec5f6732147644d1206fbd](https://github.com/mo-jinran/LiteLoaderQQNT/assets/70132037/f528580a-9f77-4047-9530-c58262ece5a8)

### 补充说明（可选）

是否不支持 Apple Silicon？我看 Readme 写的是`支持Windows, Linux, MacOS的32位与64位QQNT`，不知道是 `MacOS的32位与64位` 还是只要是 ARM 平台都不支持？
如果是这样，希望支持 Apple Silicon。
工具看起来是很棒的，非常感谢作者。

**Comment by mo-jinran** [comment]
字面意思,支持Windows, Linux, MacOS的32位与64位QQNT,没说支持什么架构,那就是QQ发布的架构都支持

**Comment by mo-jinran** [comment]
目前MacOS上QQ需要使用商店内的

**Comment by Micalhl** [comment]
> 目前MacOS上QQ需要使用商店内的

没问题，感谢，我再试一下

**Comment by Micalhl** [comment]
<img width="876" alt="image" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/70132037/7030586d-d345-4a82-945c-825c72691f93">
没毛病了，感谢🙏
