### ISSUE TITLE
最新版QQNT 似乎给Packet.json上了一个加密 加一个注释就不让开启[Bug]: 

### ISSUE THREAD

**Issue by YuSanr** [mo-jinran/LiteLoaderQQNT#65]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1

### LiteLoaderQQNT 版本 （或 Commit Id）

4.0.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

更新QQNT
到最新版本

如教程修改packet.json
怎么修改都可以
![838c2e0987d99a4065acd47c0173f74d](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112278452/fc1c786d-6560-4226-ba5c-be6f324a0325)
就如上图
只是加了一个注释就无法运行

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

无法启动

### 补充说明（可选）

这次QQ更新了一个叫什么launcher.json的文件
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/112278452/3d45df84-7c6d-4b07-89d7-d504c2aeb57c)
有一种校验的东西
只要文件校验不对就不让启动QQ

**Comment by Winter-is-comingXK** [comment]
作者应该解决这个问题了吧
