### ISSUE TITLE
轻量工具箱是谁的呀？

### ISSUE THREAD

**Issue by pohgxz** [mo-jinran/LiteLoaderQQNT#72]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

就是轻量工具箱加一个艾特高亮吧，高亮颜色为浅蓝色，然后可以带点弧度，会很好看

**Comment by xiyuesaves** [comment]
[轻量工具箱](https://github.com/xiyuesaves/lite_tools)是我的项目，你不应该在这里提交其他项目的issue，请关闭它

**Comment by pohgxz** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我确定这是一个从未被提出和实现过的功能。
> * [x]  我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
> * [x]  我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> * [x]  我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### 需要添加的功能内容
> 就是轻量工具箱加一个艾特高亮吧，高亮颜色为浅蓝色，然后可以带点弧度，会很好看

**Comment by pohgxz** [comment]
> [轻量工具箱](https://github.com/xiyuesaves/lite_tools)是我的项目，你不应该在这里提交其他项目的issue，请关闭它

抱歉嗷。我关了
