### ISSUE TITLE
[Bug]: QQ 9.9.1 补丁脚本无效 (仅Windows)

### ISSUE THREAD

**Issue by RainbowFunny826** [mo-jinran/LiteLoaderQQNT#74]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15293

### LiteLoaderQQNT 版本 （或 Commit Id）

0.4.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

打开patch文件夹
使用普通用户身份以windows powershell运行9.9.1-15293_x64.ps1
脚本无法读取位于这些需要管理员权限的文件 产生报错信息

使用管理员用户身份以windows powershell运行9.9.1-15293_x64.ps1
脚本尝试定位C:\QQ.exe.bak
找不到文件 报错

### 期望的结果是什么？

正常进行修补

### 实际的结果是什么？

powershell循环报错

### 日志记录

使用“3”个参数调用“Open”时发生异常:“未能找到文件“C:\QQ.exe.bak”。”
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:18 字符: 1
+ $sourceStream = [System.IO.File]::Open($sourceFilePath, [System.IO.Fi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

不能对 Null 值表达式调用方法。
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:32 字符: 5
+     $readBytes = $sourceStream.Read($buffer, 0, $bufferSize)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

尝试除以零。
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:77 字符: 5
+     $percentComplete = ($bytesProcessed / $fileSize) * 100
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

Write-Progress : 无法对参数“PercentComplete”执行参数验证。该参数为 Null、为空或参数集合的某个元素包含 Null 值。请提供
一个不包含任何 Null 值的集合，然后重试此命令。
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:78 字符: 79
+ ... ity "正在修补QQ.exe..." -Status "当前进度：" -PercentComplete $percentComplete
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Progress]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WriteProgressCommand

不能对 Null 值表达式调用方法。
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:32 字符: 5
+     $readBytes = $sourceStream.Read($buffer, 0, $bufferSize)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

尝试除以零。
所在位置 C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch\9.9.1-15293_x64.ps1:77 字符: 5
+     $percentComplete = ($bytesProcessed / $fileSize) * 100
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

### 补充说明（可选）

使用以下方式运行脚本
PS C:\Program Files\Tencent\QQNT\resources\app\LiteLoader\patch> .\9.9.1-15293_x64.ps1

把脚本的
$sourceFilePath $targetFilePath 改成实际路径即可解决报错

**Comment by KelseySking** [comment]
我补充一下，最好使用管理员模式的powershell，若提示无权限使用脚本，执行set-ExecutionPolicy RemoteSigned这个命令后再次运行脚本即可

**Comment by mo-jinran** [comment]
新版更建议使用Launcher而不是patch，有些人运行powershell脚本问题比较多，不好处理
