### ISSUE TITLE
关掉关掉一定要关掉

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#78]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.0-14619

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

使用LiteLoaderQQNT-Launcher_x64.exe启动QQNT后 关闭QQNT

### 期望的结果是什么？

关闭QQNT后  LiteLoaderQQNT-Launcher_x64.exe也会关闭

### 实际的结果是什么？

LiteLoaderQQNT-Launcher_x64.exe不会关闭
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/77c93a19-84f0-465b-85be-2f191929b86f)

**Comment by mo-jinran** [comment]
Release 的 最新版已修复（而且 9.9.0 不需要使用 Launcher 或 Patch）
