### ISSUE TITLE
[Feat]: ps1文件自动更新到对应的qq版本/release提供对应版本的url下载

### ISSUE THREAD

**Issue by yige-yigeren** [mo-jinran/LiteLoaderQQNT#80]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

版本发布的同时添加对应版本的qq下载链接
如题，我直接点更新结果更新到了最新版本（骂骂咧咧的重新卸了安装）
可以直接在ps1中添加版本判断以及自动更新，或至少在release页面添加对应链接
找到一个挂url的帖子
https://bbs.pcbeta.com/viewthread-1969561-1-1.html

**Comment by mo-jinran** [comment]
LiteLoader本身就支持最新版，默认推荐使用官网最新版
最高支持到最新9.9.1-15717
