### ISSUE TITLE
[Bug]: 今日新安装qqnt后，按照步骤安装后显示QQ已损坏

### ISSUE THREAD

**Issue by str0078** [mo-jinran/LiteLoaderQQNT#84]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

今日在官网下载、安装qqnt后，按照步骤安装后显示QQ已损坏
安装步骤参照的：https://github.com/mo-jinran/LiteLoaderQQNT#%E9%92%88%E5%AF%B9-windows-%E7%89%88-qqnt-991-%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E7%9A%84%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

在QQnt安装后，先手机登录，一切正常。关闭QQ后，安装好载入项，运行LiteLoaderQQNT-Launcher_x64.exe就弹出：文件已损坏，请重新安装QQ。

删除加载项和launcher后，直接运行qq.exe还是同样的报错。必须重新安装一次QQnt才可以进去。

### 期望的结果是什么？

修复

### 实际的结果是什么？

未修复

### 日志记录

PS D:\QQNT> [app]module file name: D:\QQNT\QQ.exe
359c082ae5a1d506a05c9112fd1d8bafef56e3dc31a4a510881f6ebd5e15aebe
error code v2:-8

**Comment by 2055135** [comment]
+1

**Comment by AiYuxi2010** [comment]
我也是，但是可以去https://napneko.github.io/zh-CN/guide/getting-started中下载qq（不要下napcat），目前这个qq可以装liteloader
