### ISSUE TITLE
[Feat]: 卡住啦

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#86]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

LiteLoader的核心组件没必要加开关吧 样式框架关了容易卡在这个界面
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/2d156572-c389-4b2c-bd77-2a77b8102b01)

**Comment by mo-jinran** [comment]
开关是故意保留的，有些好奇心旺盛的就会去点

**Comment by mo-jinran** [comment]
你可以在数据目录的config.json内找到被禁用的插件，删掉即可，或直接删除文件也可以
