### ISSUE TITLE
[Bug]: LiteLoader在安装于D盘的QQNT不起作用

### ISSUE THREAD

**Issue by BLdada** [mo-jinran/LiteLoaderQQNT#89]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15717 (64 Bit)

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0 (64 Bit)

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

按照https://github.com/mo-jinran/LiteLoaderQQNT#%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95 的标准安装流程安装LiteLoader于一个位于D:\Program Files (x86)\Tencent\QQNT的QQNT.

### 期望的结果是什么？

LiteLoaderQQNT在该版本能够正常使用。

### 实际的结果是什么？

无事发生

### 日志记录

[QQNT 日志.txt](https://github.com/mo-jinran/LiteLoaderQQNT/files/12286906/QQNT.txt)
（如果真的需要的话）

### 补充说明（可选）

另外，我在LiteLoader安装目录下的package.json看到的QQNT版本是9.9.0-14619，不知道有没有联系

**Comment by mo-jinran** [comment]
LiteLoaderQQNT不兼容BetterQQNT

**Comment by BLdada** [comment]
> LiteLoaderQQNT不兼容BetterQQNT

说错了😅就是LiteLoaderQQNT

**Comment by mo-jinran** [comment]
看日志貌似并未正确修改package.json，LiteLoaderQQNT并未加载，请检查`QQNT安装目录/resources/app/package.json`文件main字段

**Comment by BLdada** [comment]
main字段为LiteLoader.
另附package.json内容截图：
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/65645068/1e2043bd-cba0-4bfe-a132-af049bc292fd)

**Comment by stlion** [comment]
同样的情况，文件夹位置、修改字段、管理员身份运行.PS1文件都已尝试，无果。
修改字段，“安装教程”和“安装方法”里的内不同（有无./之分），不过都尝试了，无果。

QQNT v9.9.1-15820 (64位)
LiteLoader 0.5.1

**Comment by Clorasun** [comment]
一样

**Comment by BLdada** [comment]
更新：在更新了 9.9.2.15962（应该）版本后，我分别使用了Patch和Launcher方法试图加载LiteLoader（此时LiteLoader也更新至0.5.1）. Patch方法无作用，使用Launcher开启QQ后打开设置时，在看到LiteLoader有关的部分时会直接崩溃。

**Comment by mo-jinran** [comment]
更新 LiteLoaderQQNT 0.5.2 版本解决
