### ISSUE TITLE
[Bug]: 闪退

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#93]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

启动器启动

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

不开启任何插件 一段时间过后闪退

**Comment by shi-an** [comment]
[log.txt](https://github.com/mo-jinran/LiteLoaderQQNT/files/12291866/log.txt)

**Comment by mo-jinran** [comment]
15820版本，已经被tx针对性检测，检测到LiteLoaderQQNT，会不定时随机时间关闭QQ

**Comment by lkyu-ly** [comment]
15820版本是这样，看了好几次log没有任何征兆

**Comment by LiaoYifan2021** [comment]
怎么还没解决，希望快点解决这个问题

**Comment by lkyu-ly** [comment]
昨天就已经解决了，请仔细看readme。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 中午1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mo-jinran/LiteLoaderQQNT] [Bug]: 闪退 (Issue #93)




 
怎么还没解决，希望快点解决这个问题

**Comment by kiriYui0** [comment]
> 昨天就已经解决了，请仔细看readme。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月11日(周五) 中午1:41 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [mo-jinran/LiteLoaderQQNT] [Bug]: 闪退 (Issue #93) 怎么还没解决，希望快点解决这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

目前打开之后还是闪退,今天刚装的

**Comment by shi-an** [comment]
直接clone仓库

**Comment by TianMiaoYa** [comment]
问题仍然存在

**Comment by lkyu-ly** [comment]
很神奇，我这边问题已经不存在了，跟作者在readme中讲的一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月12日(周六) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mo-jinran/LiteLoaderQQNT] [Bug]: 闪退 (Issue #93)




 
问题仍然存在

**Comment by shi-an** [comment]
> 问题仍然存在

什么QQ版本

**Comment by TianMiaoYa** [comment]
> 这是所有的参数
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/83683108/1b389a59-8ff2-46a1-a481-0eec7d8b5f64)

**Comment by shi-an** [comment]
> > 这是所有的参数
> > ![image](https://user-images.githubusercontent.com/83683108/260216509-1b389a59-8ff2-46a1-a481-0eec7d8b5f64.png)
> > 问题为会时不时闪退，且没有任何提示

在Releases下载的？

**Comment by TianMiao8152** [comment]
> > > 这是所有的参数
> > > ![image](https://user-images.githubusercontent.com/83683108/260216509-1b389a59-8ff2-46a1-a481-0eec7d8b5f64.png)
> > > 问题为会时不时闪退，且没有任何提示
> 
> 在Releases下载的？

对

**Comment by shi-an** [comment]
> > > > 这是所有的参数
> > > > ![image](https://user-images.githubusercontent.com/83683108/260216509-1b389a59-8ff2-46a1-a481-0eec7d8b5f64.png)
> > > > 问题为会时不时闪退，且没有任何提示
> > 
> > 
> > 在Releases下载的？
> 
> 对

Releases暂时只支持到 9.9.1-15717    15820请直接clone仓库

**Comment by shi-an** [comment]
> > > > > 这是所有的参数
> > > > > ![image](https://user-images.githubusercontent.com/83683108/260216509-1b389a59-8ff2-46a1-a481-0eec7d8b5f64.png)
> > > > > 问题为会时不时闪退，且没有任何提示
> > > 
> > > 
> > > 在Releases下载的？
> > 
> > 
> > 对
> 
> Releases暂时只支持到 9.9.1-15717 15820请直接clone仓库

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/013f1e38-a09c-453c-b280-7626e38d1a2a)

**Comment by TianMiao8152** [comment]
> 

好的，clone仓库后问题已解决

**Comment by lkyu-ly** [comment]
> Releases暂时只支持到 9.9.1-15717 15820请直接clone仓库

更神奇了，我发现问题的第二天看到readme修复，自己什么也没做，打开就好了（）

**Comment by TianMiao8152** [comment]
> 

QQNT开发人员紧急修复了BUG

**Comment by shi-an** [comment]
修复了第三方插件加载器正常使用的 bug（
