### ISSUE TITLE
[Bug]: 卡顿与动画问题

### ISSUE THREAD

**Issue by Memories-white** [mo-jinran/LiteLoaderQQNT#96]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15717 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

 win11的应用最小化没有了，设置界面或是整体使用会有一定的卡顿，例如打开设置时会黑一段时间再显示，还有打字时也会出现卡顿问题

### 期望的结果是什么？

得到修复

### 实际的结果是什么？

成功修复

### 日志记录

[日志.txt](https://github.com/mo-jinran/LiteLoaderQQNT/files/12303631/default.txt)

**Comment by mo-jinran** [comment]
你这是用的修改版QQ？日志文件发现有其他不应该出现的输出内容

**Comment by yiobai** [comment]
并不是，可能是我修改了全局字体的问题导致出现了乱码
________________________________
发件人: 沫烬染 ***@***.***>
发送时间: 2023年8月12日 19:32
收件人: mo-jinran/LiteLoaderQQNT ***@***.***>
抄送: 忆白 ***@***.***>; Author ***@***.***>
主题: Re: [mo-jinran/LiteLoaderQQNT] [Bug]: 卡顿与动画问题 (Issue #96)


你这是用的修改版QQ？日志文件发现有其他不应该出现的输出内容

―

**Comment by mo-jinran** [comment]
并非乱码，我能够解析内容，而且原版QQ肯定不会输出“加载个人及系统配置文件用了 1827 毫秒。”

**Comment by mo-jinran** [comment]
而且你Windows系统，为什么要装Linux的插件背景毛玻璃？？

**Comment by yiobai** [comment]
> 并非乱码，我能够解析内容，而且原版QQ肯定不会输出"加载个人及系统配置文件用了 1827 毫秒。“ 以及 wmctrl 相关输出，这很奇怪，只有Linux才有这

因为我使用了终端的一个包，可以使它变成那样

**Comment by yiobai** [comment]
> 而且你Windows系统，为什么要装Linux的插件背景毛玻璃？？

因为是想装来试试看并没有仔细看说明，后面就没有使用了

**Comment by yiobai** [comment]
> 并非乱码，我能够解析内容，而且原版QQ肯定不会输出“加载个人及系统配置文件用了 1827 毫秒。” 以及 wmctrl 相关输出，这很奇怪，只有Linux才有这

然后就是我发现，这是插件装太多导致的问题

**Comment by yiobai** [comment]
也不能说是装太多，是启用的太多了
