### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Eternityioi** [mo-jinran/LiteLoaderQQNT#97]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

按照教程步骤修改package.json并将LiteLoader文件夹置于D:\Program Files\Tencent\QQNT\resources\app下
启动后使用LiteLoaderQQNT-Launcher_x64.exe或QQ.exe启动均提示“文件损坏，请重新安装”(非安装后首次启动)

### 期望的结果是什么？

按步骤使用LiteLoaderQQNT-Launcher_x64.exe可正常启动

### 实际的结果是什么？

按教程修改文件后使用LiteLoaderQQNT-Launcher_x64.exe或QQ.exe启动均提示“文件损坏，请重新安装”

### 日志记录

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/107354918/f2a7aeb0-04af-40a4-bc5a-d72f21582586)

**Comment by Eternityioi** [comment]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎8/‎1
操作系统版本	22621.1
体验	Windows Feature Experience Pack 1000.22632.1000.0

**Comment by Jingxu23** [comment]
使用登录器的话，不修改package.json

**Comment by zhulinyv** [comment]
我有同样的问题, QQ NT 版本: 15489, LiteLoader 版本: 0.5.0, 使用 patch 后提示文件损坏.

![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/66541860/39590901-4a0a-4377-a297-30f2e033551e)

**Comment by mo-jinran** [comment]
看来你们并未正确阅读教程，如果使用launcher，请把package.json内容还原
