### ISSUE TITLE
[Bug]: 使用登录器登录15820版本不起作用

### ISSUE THREAD

**Issue by Jingxu23** [mo-jinran/LiteLoaderQQNT#98]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820 （64）

### LiteLoaderQQNT 版本 （或 Commit Id）

#94

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

下载最新版LiteLoader，放到app中，改名为LiteLoader
下载Launcher，放到QQ.exe同目录下
通过Launcher打开qq

### 期望的结果是什么？

LiteLoader和插件正确加载

### 实际的结果是什么？

啥也没有

### 日志记录

PS C:\Program Files\Tencent\QQNT> .\LiteLoaderQQNT-Launcher_x64.exe
PS C:\Program Files\Tencent\QQNT>
[Launcher] 开始启动QQ...
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
457821688f5fdfaf1d37d349e68b7a6b63c8dff2ebca177923f43cb987fc9191
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
f7ed28ac68f19c0e836789333bfaa38774094317d1b22e510e0a80b89d9cf864
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.1-15820
[preload] hotupdate current version: 9.9.1-15820
[preload] install app version: 9.9.1-15820

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.1-15820\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.1-15820\wrapper.node
[preload] register done. launcher.node
[2023/8/10 09:16:17][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/8/10 09:16:17][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.1-15820.zip 不存在，无法执行解压操作
[2023/8/10 09:16:17][INFO] 从版本目录加载主进程代码: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.1-15820\application\background.js, {
  "curVersion": "9.9.1-15820",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/8/10 09:16:17][INFO]
---------- 华丽的分割线 ----------

09:16:24.231 > [hot update] hotUpdateApi checkHasMultipleQQ false
09:16:24.233 > [hot update] hotUpdateApi start clearOldVersions
09:16:24.233 > [hot update] hotUpdateApi curVersionZipPath is: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.1-15820.zip false
09:16:24.324 > [hot update] hotUpdateApi checkHasMultipleQQ false
09:16:24.325 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.1-15293
09:16:24.325 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false

### 补充说明（可选）

多次登录，多次管理员登录，多次x64，x86更换登录都没用，就是不加载。
插件全部移除登录也不管用。

**Comment by shi-an** [comment]
https://github.com/mo-jinran/LiteLoaderQQNT/tree/ac0799b951f4eeb92066dbd38677a5d7da65fe89/builtins
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/c146b717-da35-4cc5-a775-259719765095)
