### ISSUE TITLE
[Bug]: 官方功能失效

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT#99]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.1-15820

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

正常启动启动器

### 期望的结果是什么？

频道功能正常

### 实际的结果是什么？

频道功能打不开 但是占用资源
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/79352488/8eac913c-7a58-4048-ba86-744e7237d40b)

### 补充说明（可选）

全部插件均关闭 只剩本体问题依旧

**Comment by wuhen007** [comment]
你不说我还不知道，发现有同样的问题

**Comment by CC-maple** [comment]
我刚刚也发现频道一直打不开

**Comment by mo-jinran** [comment]
目前可以通过clone安装解决该问题，或根据 [修复QQ频道打不开的问题](https://github.com/mo-jinran/LiteLoaderQQNT/commit/d0a9126dbd6ba8f4299ba2cf90e4f8fb3b60206e) 此commit进行手动修复

**Comment by mo-jinran** [comment]
更新 LiteLoaderQQNT 0.5.2 版本解决
